env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - plugin:react/jsx-runtime
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  react/jsx-filename-extension: off
  import/extensions: off
  jsx-a11y/label-has-associated-control: off
  react/jsx-props-no-spreading: off
settings:
  import/resolver:
    typescript: {}
