name = "clocky-api"
main = "index.ts"
compatibility_date = "2022-07-10"
account_id = "b918eaac9c05f6f2b3f9a40cc4f764d0"
workers_dev = true

[[r2_buckets]]
binding = 'MY_BUCKET' # <~ valid JavaScript variable name
bucket_name = 'clocky-bucket'
preview_bucket_name = 'clocky-bucket-staging'
